# Generated by Django 5.0.3 on 2024-07-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_sex',
            field=models.CharField(max_length=30),
        ),
    ]
