# Generated by Django 5.0.3 on 2024-07-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_subject_subject_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='class_id',
            new_name='classes_id',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='class_name',
            new_name='classes_name',
        ),
    ]
