# Generated by Django 5.0.3 on 2024-07-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_rename_class_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Class_Combined',
            fields=[
                ('student_class_combined_id', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student')),
            ],
        ),
    ]
