# Generated by Django 5.0.3 on 2024-07-20 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_classes_subject_combined'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes_subject_combined',
            name='teacher',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher'),
        ),
    ]
