# Generated by Django 5.0.3 on 2024-07-20 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_rename_classes_subject_combined_classes_subject_teacher_combined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_subject_teacher_combined',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher'),
        ),
    ]
