# Generated by Django 5.0.3 on 2024-07-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_delete_classes_subject_teacher_combined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_Subject_Teacher_Combined',
            fields=[
                ('classes_subject_combined_id', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher')),
            ],
        ),
    ]
