# Generated by Django 5.0.3 on 2024-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_classes_subject_teacher_combined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes_subject_teacher_combined',
            old_name='classes_subject_combined_id',
            new_name='classes_subject_teacher_combined_id',
        ),
    ]
