# Generated by Django 5.0.3 on 2024-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_rename_classes_subject_combined_id_classes_subject_teacher_combined_classes_subject_teacher_combined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('school_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_user_email', models.EmailField(max_length=254, unique=True)),
                ('school_user_password', models.CharField(max_length=35)),
                ('school_user_username', models.CharField(max_length=40)),
                ('school_user_type', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='picture_school')),
            ],
        ),
    ]
